### PR TITLE
Add performance test

### LINKED ISSUE #277: Can we have preformance test-case for texlive from fedora-rawhide?
### Description

Everything is fine now; we are able to parse the specfile in ~30s.  But it would be nice to never break this in the future.

originally discussed here https://github.com/fedora-copr/copr/issues/2777

cc @frostyx @lachmanfrantisek I promised to fill this issue

### Benefit

_No response_

### Importance

_No response_

### Workaround

- [ ] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

### PR DESCRIPTION
**Pull request by nforro**
Fixes #277.

### CODE REVIEW

**Review by lachmanfrantisek — APPROVED** [review]

**Comment by nforro** [comment]
@lachmanfrantisek thanks for the review. I'm still playing with the test plans (it seemed the `tmt_plan` config option didn't work properly but I was probably just confused as the ordering of plan execution seems to be random).

**Comment by nforro** [comment]
Errored integration tests on EL9 are caused by a deepdiff bug: https://github.com/seperman/deepdiff/issues/416

**Pull request merged**
