### PR TITLE
Add script for extracting constants from RPM source files

### LINKED ISSUE #175: Add script(s) for auto-updating constants from RPM sources
The number of constants extracted from [RPM sources](https://github.com/rpm-software-management/rpm) in [specfile/constants.py](https://github.com/packit/specfile/blob/0a2b3864294ad3fad9560b8ba881c65c36730301/specfile/constants.py) is getting bigger,  it would be nice to have a script (or a set of scripts) to automatically extract and update the constants every week or so.

### PR DESCRIPTION
**Pull request by nforro**
Fixes #175.

### CODE REVIEW

**Review by jpopelka — APPROVED** [review]
It's all Greek to me but I tried my best :-)

**Comment by nforro** [comment]
I've updated the script so the commands are importable and added the GH action.

**Comment by nforro** [comment]
Here is a resulting PR: https://github.com/packit/specfile/pull/203

**Review by jpopelka — APPROVED** [review]
nice! :rocket:

**Comment by nforro** [comment]
Here is a final PR created by a manual workflow run: https://github.com/packit/specfile/pull/204

**Pull request merged**
