### PR TITLE
Dump debug info when accessing the `rpm_spec` property

### PR DESCRIPTION
**Pull request by nforro**
Related to https://github.com/packit/packit-service/issues/2461.

I'm not sure if this will help, but it's better than nothing. I'm still unable to reproduce the exception locally.

### CODE REVIEW

**Review by lbarcziova — APPROVED** [review]
:+1:

**Comment by nforro** [comment]
Desperately trying to trigger the exception in TF :sweat_smile: 
I guess I'll merge this and get it to both stage and prod, hopefully it will happen again.

**Pull request merged**
